export const showcaseProjectMeta = {
  birIlm: {
    id: 1,
    slug: "bir-ilm",
    categoryKey: "web",
    image: "/images/projects/bir-ilm.svg",
    technologies: ["HTML", "CSS", "JavaScript"],
    status: "Live",
    year: "2025",
    githubUrl: "",
    demoUrl: "https://bir-ilm.vercel.app",
    featured: true,
    color: "from-emerald-500 to-teal-500",
  },
  uzTravel: {
    id: 2,
    slug: "uz-travel",
    categoryKey: "web",
    image: "/images/projects/uz-travel.svg",
    technologies: ["HTML", "CSS", "JavaScript"],
    status: "Live",
    year: "2024",
    githubUrl: "",
    demoUrl: "http://woosuk.izerone.co.kr:8090/~s120211616/",
    featured: false,
    color: "from-cyan-500 to-blue-500",
  },
  autoExport: {
    id: 3,
    slug: "auto-export-mobile-app-ui-redesign",
    categoryKey: "mobile",
    image: "/projects/auto-export/cover.png",
    technologies: ["Figma", "UI/UX", "Mobile", "Design System", "Dark Mode", "Light Mode"],
    status: "",
    year: "2026",
    githubUrl: "",
    demoUrl: "",
    featured: false,
    color: "from-sky-500 to-emerald-500",
    hasCaseStudyPage: false,
  },
  interfruit: {
    id: 4,
    slug: "interfruit",
    categoryKey: "web",
    image: "/images/projects/interfruit.svg",
    technologies: ["Next.js", "React", "TypeScript", "Tailwind CSS", "Neon Postgres", "Drizzle ORM"],
    status: "Live",
    year: "2026",
    githubUrl: "https://github.com/usmansnt/interfruit_uz",
    demoUrl: "https://interfruit.netlify.app",
    featured: true,
    color: "from-lime-500 to-orange-400",
  },
  turboCarsChat: {
    id: 5,
    slug: "turbo-cars-chat",
    categoryKey: "web",
    image: "/images/projects/turbo-cars-chat.svg",
    technologies: ["React", "Vite", "Node.js", "Express", "Socket.IO", "Prisma", "PostgreSQL"],
    status: "Live",
    year: "2026",
    githubUrl: "",
    demoUrl: "https://turbocarschat.netlify.app",
    featured: true,
    color: "from-red-500 to-orange-500",
  },
} as const;
