export const showcaseProjectMeta = {
  birIlm: {
    id: 1,
    slug: "bir-ilm",
    categoryKey: "web",
    image: "/images/projects/bir-ilm.svg",
    technologies: ["HTML", "CSS", "JavaScript"],
    status: "Live",
    year: "2025",
    githubUrl: "",
    demoUrl: "https://bir-ilm.vercel.app",
    featured: true,
    color: "from-emerald-500 to-teal-500",
  },
  uzTravel: {
    id: 2,
    slug: "uz-travel",
    categoryKey: "web",
    image: "/images/projects/uz-travel.svg",
    technologies: ["HTML", "CSS", "JavaScript"],
    status: "Live",
    year: "2024",
    githubUrl: "",
    demoUrl: "http://woosuk.izerone.co.kr:8090/~s120211616/",
    featured: false,
    color: "from-cyan-500 to-blue-500",
  },
} as const;
